if Rails.env.development?
  TWITTER_KEY="vqVoZV5X3veMwQtktXFA6Q"
  TWITTER_SECRET="Vjbiu6QniUJ4FXRMAWuYbGbGGP2gIKhpGutvC0drlU"
  TWITTER_KEY_URL_ENCODED="vqVoZV5X3veMwQtktXFA6Q"
  TWITTER_SECRET_URL_ENCODED="Vjbiu6QniUJ4FXRMAWuYbGbGGP2gIKhpGutvC0drlU"
  TWITTER_BEARER_TOKEN_CREDENTIALS="vqVoZV5X3veMwQtktXFA6Q:Vjbiu6QniUJ4FXRMAWuYbGbGGP2gIKhpGutvC0drlU"
  TWITTER_ENCODED_BEARER_TOKEN_CREDENTIALS="dnFWb1pWNVgzdmVNd1F0a3RYRkE2UTpWamJpdTZRbmlVSjRGWFJNQVd1WWJHYkdHUDJnSUtocEd1dHZDMGRybFU="
  TWITTER_BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAEckQQAAAAAAqgqXz73bjqWwvm25I7GpREBYSxs%3DpSJ1gBlCvq43FtCdbNUKIvyRgwbzQ8dxsAWR6eK0no"

  SCHEDULER_PERIOD = 10.minutes 
  BORN_LAT_MAX = 46.195042
  BORN_LAT_MIN = 45.073521
  BORN_LONG_MAX = 7.684078
  BORN_LONG_MIN = 6.135006
end